// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnhretvvucjpnkachoov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuaHJldHZ2dWNqcG5rYWNob292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDkyODEsImV4cCI6MjA2NTU4NTI4MX0.sqwA2ZJ_l2cIvw2gLDWuqgH22Qe5e3yxi2bUW3RnE74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);